### ISSUE TITLE
Do first test on Rapsberry PI 5.

### ISSUE THREAD

**Issue by enjoy-digital** [enjoy-digital/litex_m2sdr#18]
- [x] Raspberry Pi OS (not buildroot since we'll want to use SDR softwares).
- [x] Check m2sdr_util info.
- [x] Check m2sdr_util dma_test (if not working or freezing, still continue testing the other points).
- [x] Check m2sdr_rf -samplerate=10e6
- [x] Check m2sdr_record (should display the record speed).
- [x] Install GQRX and test (if working, see what maximum samplerate work).
- [ ] Install SDRPP and test (if working, see what maximum samplerate work).
- [x] Install GnuRadio and test.

**While testing, describe all the steps in the current issues to be able to reproduce later and include in a README for future users.**

**Comment by enjoy-digital** [comment]
Initial tests have been done on Raspberry CM4 and Pi 5. We can close now and will open more specific isssues when/if required.

**Comment by akioolin** [comment]
Dear Sir:

where could I find the used board for RPi-5 / CM4?
which carrier board is used for CM4 module?
which pice <-> M.2 M-Key board for RPi-5??

Many Thanks.

BR, Akio

**Comment by enjoy-digital** [comment]
Hi @akioolin,

For the RPi-5 we were using this hat: https://pineboards.io/products/hatdrive-bottom-2230-2242-2280-for-rpi5
For the CM4, the board was mounted in a one of our baseboard available [here](https://enjoy-digital-shop.myshopify.com/products/litex-acorn-baseboard-minil).

**Comment by akioolin** [comment]
Hi, @enjoy-digital :

Many Thanks. This info is very useful!!

BR, Akio
