### ISSUE TITLE
CMake version for soapy driver on Jetson / Ubuntu 20.04.6 LTS

### ISSUE THREAD

**Issue by f4gkr** [enjoy-digital/litex_m2sdr#25]
Required version is set to 3.17 , and by default Ubuntu 20.04.6 LTS ships with CMake 3.16.3
I changed the min version to 3.16 and it compiles

``` bash
cmake_minimum_required(VERSION 3.16)
```

**Comment by enjoy-digital** [comment]
Thanks @f4gkr, will look at this.

**Comment by enjoy-digital** [comment]
Updated with https://github.com/enjoy-digital/litex_m2sdr/commit/938d6a200154f0e6c5f43fea67ecb2b7c0024d87.
